---
- name: CFME | Configure Repositories | Include Tasks for Installing Custom Facts
  include_tasks: tasks/install-custom-facts.yml

- name: CFME | Configure Repositories | Disable All
  command: "subscription-manager repos --disable='*'"
  become: True

- name: CFME | Configure Repositories | Set CFME Product Version
  set_fact:
    cfme_version_product: "{{ ansible_local['cfme']['cfme_version_product'] }}"
  when: cfme_version_product is not defined

- name: CFME | Configure Repositories | Set Required Base Repositories
  set_fact:
    cfme_base_repositories:
      - rhel-7-server-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-extras-rpms
      - "cf-me-{{ cfme_version_product }}-for-rhel-7-rpms"

- name: CFME | Configure Repositories | Set Version Specific Repositories
  set_fact:
    cfme_version_repositories:
        - rhel-7-server-ansible-2.7-rpms
        - rhel-7-server-rh-common-rpms
    when: {{ cfme_version_product }} = 5.10

- name: CFME | Configure Repositories | Set Required Repositories
  set_fact:
    cfme_repositories: "{{ cfme_base_repositories | union ( additional_repos if {{ cfme_version_product }} = 5.10 else [] ) }}"

- name: CFME | Configure Repositories | Enable Required Repositories
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items: "{{ cfme_repositories }}"
  become: True

- name: CFME | Configure Repositories | Enable Additional Repositories
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items: "{{ cfme_additional_repositories }}"
  become: True
  when: cfme_additional_repositories is defined
