---

- name: CFME | Health Check | Port 443 is listening
  wait_for:
    host: "{{ ansible_fqdn }}"
    port: 443
    state: started
    timeout: "{{ cfme_port_ready_timeout_seconds | default(600) }}"

- name: CFME | Health Check | Ping Check
  uri:
    url: "https://{{ ansible_fqdn }}:443/ping"
    method: GET
    validate_certs: False
    body_format: raw
    return_content: Yes
  register: cfme_ping_check_result
  until: "cfme_ping_check_result['content'] is defined and cfme_ping_check_result['content'] == 'pong'"
  retries: "{{ cfme_healthcheck_retries | default(100) }}"
  delay: 5

