---

- import_tasks: tasks/determine-pg-service-name.yml

- name: CFME | Update Packages | Stop evmserverd
  service:
    name: evmserverd
    state: stopped
  when: "'cfme-appliances' in group_names"

- name: CFME | Update Packages | Stop postgres
  service:
    name: "{{ cfme_pg_service_name }}"
    state: stopped
  when: "'cfme-databases' in group_names"

- name: CFME | Update Packages | Latest
  command: "yum update -y --releasever={{ releasever }}"
  when: releasever is defined
  
- name: CFME | Update Packages | Latest
  yum:
    name: "*"
    state: latest
  when: releasever is undefined
  
- name: CFME | Update Packages | Include Tasks for Host Reboot
  include_tasks: tasks/host-reboot.yml

- name: CFME | Update Packages | Start postgres
  service:
    name: "{{ cfme_pg_service_name }}"
    state: started
  when: "'cfme-databases' in group_names"

- name: CFME | Update Packages | Start evmserverd
  service:
    name: evmserverd
    state: started
  when: "'cfme-appliances' in group_names"

