---
- name: CFME | Update | All Preparation
  hosts: cfme
  become: True
  gather_facts: True
  tasks:
    - name: CFME | Update | Include Tasks for Subscribing Using Activation Key
      include_tasks: tasks/configure-activation-key.yml
      when: sat6_activation_key is defined

    - name: CFME | Update | Include Tasks for Configuring Repositories
      include_tasks: tasks/configure-repositories.yml
      when: sat6_activation_key is not defined

    - name: CFME | Update | Any package updates required?
      command: "yum check-update --releasever={{ releasever }}"
      args:
        warn: no
      register: packages_need_update_result
      changed_when: packages_need_update_result.rc == 100
      failed_when: packages_need_update_result.rc != 0 and packages_need_update_result.rc != 100
      when: releasever is defined

    - name: CFME | Update | Any package updates required?
      command: "yum check-update"
      args:
        warn: no
      register: packages_need_update_result
      changed_when: packages_need_update_result.rc == 100
      failed_when: packages_need_update_result.rc != 0 and packages_need_update_result.rc != 100
      when: releasever is undefined

- name: CFME | Update | Update Databases
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Update | Include Tasks for Updating Packages
      include_tasks: tasks/update-packages.yml
      when: packages_need_update_result | changed

- name: CFME | Update | Update Appliances
  hosts: cfme-appliances:!cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Update | Include Tasks for Updating Packages
      include_tasks: tasks/update-packages.yml
      when: packages_need_update_result | changed

- name: CFME | Update | Wait for API to report ready
  import_playbook: health-check.yml

- name: CFME | Update | Reset MIQ and Red Hat Automate Domains
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:

    - name: CFME | Update | rake evm:automate:reset
      run_once: True
      shell: |-
        source /etc/profile.d/evm.sh
        cd /var/www/miq/vmdb
        rake evm:automate:reset > >(tee /var/tmp/evm_automate_reset.out) 2> >(tee /var/tmp/evm_automate_reset.err >&2)
      args:
        executable: /bin/bash
