---

- name: CFME | Stop Services | Appliances
  hosts: cfme_appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Stop Services | EVM
      service:
        name: evmserverd
        state: stopped

- name: CFME | Stop Services | Databases
  hosts: cfme_databases
  become: True
  gather_facts: True
  tasks:
    - import_tasks: tasks/determine-pg-service-name.yml

    - name: CFME | Stop Services | PostgreSQL
      service:
        name: "{{ cfme_pg_service_name }}"
        state: stopped
